apiVersion: v1
appVersion: '1.0'
description: Tilehuria Helm chart for Kubernetes
name: charts
version: 0.1.0
dependencies:
  - name: minio
    version: '3.4.13'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: minio.enabled
  - name: rabbitmq
    version: '7.4.5'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: rabbitmq.enabled
  - name: postgresql
    version: '8.10.13'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
