---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  access-token: {{ required ".Values.cert.digitalOceanToken is required" .Values.cert.digitalOceanToken | b64enc }}
    
