{{- $jwtKey := include "hasura.jwtKey" . -}}
{{- $jwtAlgo := include "hasura.jwtKey" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hasura
type: Opaque
data:
    hasuraAdminSecret: {{ required ".Values.hasuraAdminSecret is required" .Values.hasuraAdminSecret | b64enc}}
    jwt.key: {{ $jwtKey | b64enc }}
    # scrappy, but it works
    jwt.secret: {{ printf "{\"type\": \"%s\", \"key\": \"%s\"}" $jwtAlgo $jwtKey | squote | replace "\\\"" "\"" | b64enc }}
    
