{{- $jwtKey := include "hasura.jwtKey" . -}}
{{- $jwtAlgo := include "hasura.jwtAlgo" . -}}
{{- $adminSecret := include "hasura.adminSecret" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hasura
type: Opaque
data:
    adminSecret: {{ $adminSecret | b64enc | quote }}
    jwt.key: {{ $jwtKey | b64enc | quote }}
    jwt.secret: {{ printf "{\"type\": \"%s\", \"key\": \"%s\"}" $jwtAlgo $jwtKey | replace "\\\"" "\"" | b64enc }}
    {{- include "hasura.databaseSecrets" . | nindent 4 }}
