{{- $secret := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-postgresql") }}
{{- $postgresPassword := randAlphaNum 16 }}
{{- if $secret }}
    {{- $postgresPassword:= (index $secret.data "postgresql-password") | b64dec }}
{{- else }}
    {{- if .Values.postgresql.postgresqlPassword }}
        {{- $postgresPassword := .Values.postgresql.postgresqlPassword }}
    {{- end -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-password: {{ $postgresPassword | b64enc | quote }}
  databaseUrl: {{ (printf "postgres://%s:%s@%s-postgresql:%d/%s" (.Values.postgresql.postgresqlUsername | default "postgres") $postgresPassword .Release.Name (.Values.postgresql.servicePort |int) (required ".Values.postgresql.postgresqlDatabase is required" .Values.postgresql.postgresqlDatabase)) | b64enc | quote }}
