{{- $postgresPassword := include "hasura.postgresPassword" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-password: {{ $postgresPassword | b64enc | quote }}
  databaseUrl: {{ (printf "postgres://%s:%s@%s-postgresql:%d/%s" (.Values.postgresql.postgresqlUsername | default "postgres") $postgresPassword .Release.Name (.Values.postgresql.servicePort |int) (required ".Values.postgresql.postgresqlDatabase is required" .Values.postgresql.postgresqlDatabase)) | b64enc | quote }}
