{{- if .Values.postgresql.enabled -}}
{{- $url := include "postgresql.url" . -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
    postgresql-password: {{ required ".Values.postgresql.postgresqlPassword is required" .Values.postgresql.postgresqlPassword | b64enc }}
    url: {{ $url | b64enc }}
{{- end }}
