apiVersion: v1
appVersion: '1.0'
description: Hasura & Hasura Backend Plus Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/hasura/graphql-engine/master/assets/brand/hasura_icon_blue.svg
name: hasura-plus
version: 0.1.0
dependencies:
  - name: minio
    version: '3.4.13'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: minio.enabled
  - name: postgresql
    version: '8.10.13'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
