name: update-helm-repo

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package source/* -u
      - name: Index
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo index --url https://charts.platyplus.io .
      - name: Commit
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          message: "New helm charts"
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
